export const AuthUserActionTypes = {
    FIRST_NAME: 'FIRST_NAME',
    LAST_NAME: 'LAST_NAME',
    EMAIL: 'EMAIL',
    PASSWORD: 'PASSWORD',
    USERNAME: 'USERNAME',
    CONFIRM_PASSWORD: 'CONFIRM_PASSWORD',
    LOGGED_IN_USER: 'LOGGED_IN_USER'
}